# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Botalki' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Botalki

  pod 'NVActivityIndicatorView', '~> 5.1.1'
  pod 'PinLayout'
  pod 'FirebaseCore'
  pod 'FirebaseStorage'

end
